FIELDS = { 'all': ['PCT_LACCESS_POP15',
          'PCT_LACCESS_HHNV15',
          'PCT_LACCESS_SENIORS15',
          'GROCPTH14',
          'SUPERCPTH14',
          'CONVSPTH14',
          'SPECSPTH14',
          'SNAPSPTH16',
          'WICSPTH12',
          'FFRPTH14',
          'FSRPTH14',
          'SNAP_PART_RATE13',
          'PCT_SFSP15',
          'PCT_WIC15',
          'FOODINSEC_13_15',
          'SODATAX_STORES14',
          'CHIPSTAX_STORES14',
          'PCT_LOCLSALE12',
          'FMRKTPTH16',
          'PCT_FMRKT_SNAP16',
          'PCT_FMRKT_CREDIT16',
          'VEG_ACRESPTH12',
          'PCT_OBESE_ADULTS13',
          'RECFACPTH14',
          'PCT_NHWHITE10',
          'PCT_NHBLACK10',
          'PCT_HISP10',
          'PCT_NHASIAN10',
          'PCT_NHNA10',
          'PCT_NHPI10',
          'PCT_65OLDER10',
          'PCT_18YOUNGER10',
          'POVRATE15',
          'METRO13'],

          'exclude' : ['PCT_LACCESS_HHNV15',
          'PCT_OBESE_ADULTS13',
          'PCT_NHWHITE10',
          'PCT_NHBLACK10',
          'PCT_HISP10',
          'PCT_NHASIAN10',
          'PCT_NHNA10',
          'PCT_NHPI10']
          }

target_field = ['PCT_OBESE_ADULTS13']
